# Generated by Django 4.1.7 on 2023-02-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=None, null=True)),
                ('days', models.IntegerField()),
                ('linux_username', models.CharField(default=None, max_length=10, null=True)),
                ('linux_password', models.CharField(default=None, max_length=10, null=True)),
                ('state', models.CharField(choices=[('Not started yet', 'Not Started'), ('In use', 'In Use'), ('Finished', 'Finished')], default='Not started yet', max_length=20)),
            ],
        ),
    ]
