# Generated by Django 4.1.7 on 2023-02-18 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('packs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='packs', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
