# Generated by Django 4.1.7 on 2023-02-18 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0002_pack_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pack',
            name='user',
        ),
    ]
