# Generated by Django 4.1.7 on 2023-03-03 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0005_remove_pack_state_pack_finished_pack_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='port',
            field=models.IntegerField(default=2286),
        ),
        migrations.AlterField(
            model_name='pack',
            name='linux_password',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pack',
            name='linux_username',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pack',
            name='start_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
