# Generated by Django 4.1.7 on 2023-03-28 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0007_alter_pack_port'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pack',
            name='port',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
