# Generated by Django 4.1.7 on 2023-04-06 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentRequest',
        ),
    ]
